//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<RSAKeyValue><Modulus>vovbo/Ec7wNVKPqp5b90i9DI0S0MgI1c6YdxObjdigvsI5ZIzubMSuZBISdOuhkXTjjDJOlkhghncT2OQuEvDgveCfhtD/aygHkNh2sc2toEhJDgTFrDJ+BmqlHJTglNcQ/1ZPXZI897jsH5cEUvu8vjD0nJaNLhVhfodrD+Ykk=</Modulus><Exponent>AQAB</Exponent><P>5vudg37nU692vXFu7cOr7d70iOPWxQ6qHX6FRPjxuZAvDfFQlE5+x/5tEj7OPb91ElypW7odFY9W9BI95HeHzw==</P><Q>0y8Sa3NpIg0961WMp53TyZsuCV9hBIiBe1rLzjH8XQrMDikcoOfv0gKGraRfB5oM3HTHw3T4HjVUOUq2z17iZw==</Q><DP>CEvtYnXCdV0OFMvoQh4PJOInQmt8oWNfdOPAgbO3awTky8lpLYqMPz7CSC99VPZ1jA1MAAF1XfriEq49DuHEPQ==</DP><DQ>bZ5Hb2LutXAuLdOwOOkhn8pe8RqDH3lDzKXqmFM17Y3HMaqBY7xArcAF7Ggfs7Bw8JXlgz1Z9UQ1Pa/ciHN2DQ==</DQ><InverseQ>a1IZozPPHL+pn3p8ve1MTBw1vpHcwtQObzFUlb58fEVXBwAuPkc7FuY8CzMY/Z+lLFVzSPbGHUtgM7mcoUqjNg==</InverseQ><D>FszhcVKOpcL+U7L61XT9WyWWggEj99Xygjckw0VtrPEURoXbHHbdhzDaJj9v2jDaaw+7uhT7ZFZpGlHFThdn689y6JktyPCDeOnpJx5iFtuhN2yiGy3r13owXbdyeASwehC96NtyHMDTdOzhAQ9f8PiU/RoX8V2eroz2OI20VKk=</D></RSAKeyValue>")]
        public string PRIVATE_KEY {
            get {
                return ((string)(this["PRIVATE_KEY"]));
            }
            set {
                this["PRIVATE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<RSAKeyValue><Modulus>vovbo/Ec7wNVKPqp5b90i9DI0S0MgI1c6YdxObjdigvsI5ZIzubMSuZBISd" +
            "OuhkXTjjDJOlkhghncT2OQuEvDgveCfhtD/aygHkNh2sc2toEhJDgTFrDJ+BmqlHJTglNcQ/1ZPXZI89" +
            "7jsH5cEUvu8vjD0nJaNLhVhfodrD+Ykk=</Modulus><Exponent>AQAB</Exponent></RSAKeyValu" +
            "e>")]
        public string PUBLIC_KEY {
            get {
                return ((string)(this["PUBLIC_KEY"]));
            }
            set {
                this["PUBLIC_KEY"] = value;
            }
        }
    }
}
